import Head from "next/head";
import Image from "next/image";
import Inbox from "../components/Inbox";
import Navbar from "../components/Navbar";
import Messenger from "../components/Messenger";
import SearchContacts from "../components/SearchContacts";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="bg-gray-400">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
      </Head>
      {/* Navbar */}
      <Navbar />
      <div className=" flex  ">
        {/* Inbox */}
        <Inbox />
        <div className="flex bg-black pt-2">
          {/* Search + Contacts */}
          <SearchContacts />
          {/* Messenger */}
          <Messenger />
          {/* Todos / Contacts */}
        </div>
      </div>
    </div>
  );
}
